### ISSUE TITLE
Encounter methods

### ISSUE THREAD

**Issue by christianhturner** [FoundryDevelopmentConsortium/Knowledge-Recalled-PF2e-FVTT#17]
Expected Behavior: KnowledgeRecalled Object (class) should have accessible the currently active encounters, active encounters NPC should be passed to NPCModel to either be verified as "flagged" or for flags to be appeneded to them.

**Notes**
* Active Encounters in this context do not equate to simply being in the sidebar, but these need to have "begun". 
* Remove the encounter from this array whenever an encounter ends.
* New encounters should be added to the array when they start.
* When the system starts we should fetch any encounters that are active at the game start.

**Dependencies**
GM Journal is soley a reflection of encounters that are in this array.

**Comment by AlecHolloway** [comment]
Still working on
