### ISSUE TITLE
documentedActors

### ISSUE THREAD

**Issue by christianhturner** [FoundryDevelopmentConsortium/Knowledge-Recalled-PF2e-FVTT#18]
When foundry loads documentedActors should be fetched from the JSON file data stored in the module.

**Hooks**
* On Ready -> get documentedActors from JSON file
* Successful -> Recall knowledge
* New item is added to Array -> update JSON file

**Notes**
this is a one-to-one representation of the playerJournalsView

**Comment by AlecHolloway** [comment]
Why exactly do we need to store the data in a json file? Is this for long term storage? So if the user deletes an npc from the foundry sidebar it will still be backed up to the file?

**Comment by chturner94** [comment]
It's for long term storage and for populating the NPC journal for the players. The module only populates and checks NPCs who are actively in an encounter. JSON is where we will populate the player journal.
