### ISSUE TITLE
getLowestSave

### ISSUE THREAD

**Issue by AlecHolloway** [FoundryDevelopmentConsortium/Knowledge-Recalled-PF2e-FVTT#24]
NPCModel.js -> class NPCModel -> getLowestSave() -> removeFlag()
The remove flag function takes in two parameters: actor and flagPath. Currently the flagPath is set to lowestSave.lowestSaveValue. The lowestSave is set above like so: const lowestSave = Math.min(fortitudeSaveValue, willSaveValue, reflexSaveValue); This however only sets the value and the function does not recognize the full path.  We will need to change the lowestSave to lowestSaveValue and find a way to  store the actual path ie. ( fortSave, willSave, refSave ) . value

**Comment by chturner94** [comment]
[Discord discussion thread](https://discord.com/channels/950550326434480138/1127672219598864516)
Please continue conversation here and provide work notes on the issue thread.

**Comment by chturner94** [comment]
Resolved: the issue was that the remove flag function was expecting a string of the path to the value, but I was instead just passing the value. 
Improvement: created jsdoc for remove flag.

**Comment by chturner94** [comment]
Awaiting merge
